### ISSUE TITLE
Cannot load GSM8K_DSPy data set

### ISSUE THREAD

**Issue by aiyinyuedejustin** [zou-group/textgrad#110]
Dear Author,

I am trying to run 

```shell
 python prompt_optimization.py --task=GSM8K_DSPy --run_validation --do_not_run_larger_model  --evaluation_engine=gpt-4o --test_engine=gpt-3.5-turbo-0125 
```

however, it is said "TypeError: Can't instantiate abstract class GSM8K_DSPy with abstract method get_default_task_instruction"  , is this normal?

**Comment by mertyg** [comment]
this was an error in a previous release -- was fixed [here](https://github.com/zou-group/textgrad/commit/5cd7cc08c4ff46019b491064fa965dc4c25ff915), i think updating the package would help.
