### ISSUE TITLE
 UnicodeDecodeError: 'gbk' codec can't decode byte 0x9a in position 8359: illegal multibyte sequence

### ISSUE THREAD

**Issue by datalee** [zou-group/textgrad#139]
when  pip install  textgrad，get error：
`line 319, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x9a in position 8359: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

`

**Comment by zfl12** [comment]
我也遇到了

**Comment by vinid** [comment]
This might be due to the encoding of the files and your locale on the laptop. Can you check [this](https://github.com/IDEA-Research/GroundingDINO/issues/347) and see if this solves the problem?

We might need to update the package to force utf8 encoding on file opening.

**Comment by pluto0x0** [comment]
The issues is due to opening README file with default codec (gbk) by `setup.py`. The error can be suppressed by setting environment variable `PYTHONUTF8=1` to use utf8 as default codec:

powershell:

```powershell
$env:PYTHONUTF8=1
```

linux:

```shell
export PYTHONUTF8=1
```

before running `pip install`

**Comment by datalee** [comment]
> The issues is due to opening README file with default codec (gbk) by `setup.py`. The error can be suppressed by setting environment variable `PYTHONUTF8=1` to use utf8 as default codec:
> 
> powershell:
> 
> ```powershell
> $env:PYTHONUTF8=1
> ```
> 
> linux:
> 
> ```shell
> export PYTHONUTF8=1
> ```
> 
> before running `pip install`

work，thks
