### ISSUE TITLE
Use github actions for releasing new versions

### ISSUE THREAD

**Issue by AndersBennedsgaard** [zou-group/textgrad#146]
It seems that releasing new versions is a manual process as of now. It could be nice if this is done automatically on new tags, or similar.
Additionally, it would be nice if you made use of Github releases to store changelogs, since it is very hard to see what the different versions of the package holds.

**Comment by tboen1** [comment]
Thanks for the suggestion! We're working on it, apologies for the delay we have a bit of a backlog.

**Comment by AndersBennedsgaard** [comment]
> Thanks for the suggestion! We're working on it, apologies for the delay we have a bit of a backlog.

Oh no worries @tboen1 . I would suggest leaving this issue open if you take PRs for it, such that there is a possibility for others to contribute. Otherwise, feel free to ignore this
