### ISSUE TITLE
Quick start

### ISSUE THREAD

**Issue by andresckamilo** [zou-group/textgrad#2]
I tried the code from the quick start guide in the repository, but it is not working correctly and gives me errors. The commands and the imports don't seem to match properly.

For the first code example, I encountered this error:

```python
AttributeError: 'str' object has no attribute 'value'
```

When trying it with a question, I got the following error:

```python
TypeError: 'str' object is not callable
```

**Comment by andresckamilo** [comment]
I found the solution. The problem is that in the quick start guide, the engine is defined as a string (`str`), but it shouldn't be. In the source code, the engine is an instance of `engineLM`, so using a string causes the error.

Here is the corrected code:

```python
engine = tg.get_engine(engine_name='gpt-4o')
model = tg.BlackboxLLM(engine)
```

With this change, everything else works correctly.

**Comment by mertyg** [comment]
Great catch -- I'm sorry for the delay in responding. 
We'll push the latest version to pypi soon. Also in the meantime, you can clone the repo, run `pip install -e .` and work with the latest and greatest.

apologies again

**Comment by andresckamilo** [comment]
Oh yes, I also got that, but I was able to get it done changing it by that, since the sintax is similar to Pytorch. No worries, thanks for the library! It is really nice.

**Comment by mertyg** [comment]
That’s great to hear — appreciate your interest @andresckamilo !
