### ISSUE TITLE
Do the engine supported by AzureOpenAI?

### ISSUE THREAD

**Issue by wuyanghui** [zou-group/textgrad#38]

**Comment by kgourgou** [comment]
A PR is in for that. 

https://github.com/zou-group/textgrad/pull/26

Also you can instantiate an instance of [ChatExternalClient](https://github.com/zou-group/textgrad/blob/60198d377b2ef5ad5a4ce4873b126dd8454296e7/textgrad/engine/local_model_openai_api.py#L9), but pass the AzureOpenAI client yourself. That's how I use it.

**Comment by nikhilk7153** [comment]
From the example (Local-Model-With-LMStudio.ipynb), I see how to set the backward engine, but it's not clear to me how to set the LLMs for inference. 

llm = tg.get_engine(engine_name="gpt-4o")

This is how it is done usually, but I was wondering how do I call the inference, when if I am using AzureOpenAI?

**Comment by nikhilk7153** [comment]
Or actually, I figured it out, it's just, tg.model.BlackboxLLM(engine).

**Comment by kgourgou** [comment]
You got it; we can add this to the example.

**Comment by MaazK7** [comment]
Another way that I found to make this work is that you declare 4 environments variables.

AZURE_OPENAI_API_VERSION (2023-07-01-preview)
AZURE_OPENAI_API_KEY
AZURE_OPENAI_API_BASE
OPENAI_API_KEY (HERE YOU SHOULD REPEAT YOUR AZURE_OPENAI_API_KEY)

And then 
llm = tg.get_engine(engine_name="azure-{your_model_deployment _name }")
