### ISSUE TITLE
Problems in running the quickstart

### ISSUE THREAD

**Issue by HelloWorldLTY** [zou-group/textgrad#50]
Hi, thanks for your great work! I am trying to follow the three steps shown in https://textgrad.com/index.html#application but failed in the second step:
<img width="1027" alt="image" src="https://github.com/zou-group/textgrad/assets/43333475/136d6cea-4c2f-493a-bf9f-55af79f8d759">

Did I miss anything? Thanks a lot.

**Comment by vinid** [comment]
Hello! you need to set an engine as global in this context.

```python
import textgrad as tg

tg.set_backward_engine("gpt-4o", override=True)
```

Could you point me to where the example is? We might need to update that!

**Comment by HelloWorldLTY** [comment]
Sure, I will have a try. The original design does not include requests for such steps:
```
import textgrad as tg
# Step 1: Get an initial response from an LLM
model = tg.BlackboxLLM("gpt-4o")
punchline = model(tg.Variable("write a punchline for my github package about optimizing compound AI systems", role_description="prompt", requires_grad=False))
punchline.set_role_description("a concise punchline that must hook everyone")
```

The example can be found in : https://textgrad.readthedocs.io/en/latest/index.html
