### ISSUE TITLE
Issue running GSM8K_DSPy prompt_optimization.py

### ISSUE THREAD

**Issue by zcoder351** [zou-group/textgrad#77]
I attempted to run the following `python prompt_optimization.py --task=GSM8K_DSPy --run_validation --do_not_run_larger_model  --evaluation_engine=gpt-4o --test_engine=gpt-3.5-turbo-0125` and there were a couple of issues. 1. `TypeError: Can't instantiate abstract class GSM8K_DSPy with abstract method get_default_task_instruction`. I fixed this by adding the method. 
2. Then I encountered `TypeError: textgrad.tasks.big_bench_hard.string_based_equality_fn() argument after ** must be a mapping, not list.`

**Comment by mertyg** [comment]
Sorry about these, the updates making textgrad multimodal had breaking changes for these. We just pushed a hotfix for this. Thank you so much for catching it -- let us know if you still get errors!
