### ISSUE TITLE
Add `textgrad` to conda-forge channel

### ISSUE THREAD

**Issue by sugatoray** [zou-group/textgrad#8]
A conda install option for textgrad could be helpful. It not only helps with installation of textgrad in conda environments, but also facilitates easier adoption of textgrad among downstream libraries that depend on textgrad and that may want to add themselves to conda-forge channel in future.

I have already started a conda-forge PR to add `textgrad`. Once the PR is merged, you can install textgrad as follows:

```sh
conda install -c conda-forge textgrad
```

Please assign this issue to me. I will update the documentation, once the upstream conda-forge PR is merged.

- PR: https://github.com/conda-forge/staged-recipes/pull/26673

**Comment by sugatoray** [comment]
cc: @vinid @mertyg

**Comment by vinid** [comment]
Thanks so much for this!

What do we need to do when new versions of textgrad will come out? How we deploy them on conda forge?

Thanks!

**Comment by sugatoray** [comment]
@mertyg Mostly for newer versions (once released on PyPI) the conda-forge feedstock repository will auto initiate an update to the conda-forge package for textgrad. In cases where it fails the maintainer(s) will have to look into what’s causing the failure and fix them. It is also possible for people who are not maintainers to fix/update the package and send a PR at the following repo:

https://github.com/conda-forge/textgrad-feedstock

If you would like to be a co-maintainer of the conda-forge repository for the package, I can add you there and we will co-maintain it. Given that I am the maintainer of over 80 Python libraries on conda-forge, it will certainly help if we have someone from the core textgrad team there in the list of maintainers for the conda-forge package.

**Comment by mertyg** [comment]
Awesome! Can you actually add both @vinid and me?

Thank you so much for this @sugatoray -- very very much appreciated!

**Comment by sugatoray** [comment]
> Awesome! Can you actually add both @vinid and me?

Gladly! 😊

@mertyg and @vinid If you don't mind, can you share your LinkedIn pages here? I would like to connect with both of you.

**Comment by sugatoray** [comment]
> Thanks so much for this!
> 
> What do we need to do when new versions of textgrad will come out? How we deploy them on conda forge?
> 
> Thanks!

Hi @vinid, glad that I could help out. When I responded to your question [here](https://github.com/zou-group/textgrad/issues/8#issuecomment-2178998121) I accidentally deleted  `@vinid` from the reply, which I just realized. The reponse was meant for both @mertyg and you.
