### ISSUE TITLE
Does the engine support deepseek family models?

### ISSUE THREAD

**Issue by Jo620** [zou-group/textgrad#80]
![a1080c2eaa767077abd5f56223dee11](https://github.com/user-attachments/assets/a192139b-bac9-449b-a8bc-e4e1298112eb)
I tried to replace the GPT4o model with the deepseek model but it doesn't seem to be supported. Is there any way?

**Comment by vinid** [comment]
Hello! This [PR](https://github.com/zou-group/textgrad/pull/20/files) introduced support for local models (as long as they offer a client that is compatible with OpenAI APIs. 

Deepseek should be in that category so you should be able to first create the client and then to pass it to the new class.

Let us know if you need help!

**Comment by Jo620** [comment]
Yes, I want to know how to create a client, do I need to search the deepseek website for relevant information?

**Comment by Jo620** [comment]
> Hello! This [PR](https://github.com/zou-group/textgrad/pull/20/files) introduced support for local models (as long as they offer a client that is compatible with OpenAI APIs.
> 
> Deepseek should be in that category so you should be able to first create the client and then to pass it to the new class.
> 
> Let us know if you need help!
