### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by yejin109** [zou-group/textgrad#87]
Hi there,

I've just met some errors when I follow the quick start code snippet from the ReadMe file.
To begin with, I clone this project onto my laptop.

```
Traceback (most recent call last):
    def _construct_string_fn_chain_backward_prompt(backward_info: dict[str, str]) -> str:
TypeError: 'type' object is not subscriptable
....
    def _construct_multimodal_llm_chain_backward_content(backward_info: dict[str, str]) -> str:
TypeError: 'type' object is not subscriptable
...
```
I think usign Dict from typing can solve this problem. 
I just wonder whether there exist some conflict with my python version or not. 
My current python version is 3.8.18.

Thanks!

**Comment by mertyg** [comment]
Ah definitely this is a Python <3.9 thing. We should be more clear about that we do not support <3.9 . Sorry about this!
