### ISSUE TITLE
Unable to perform inference with Prompt Optimization Example

### ISSUE THREAD

**Issue by nikhilk7153** [zou-group/textgrad#91]
Hello,

I am getting the following error when running the prompt optimization code on my own custom dataset: 

<img width="1027" alt="image" src="https://github.com/user-attachments/assets/bcdbe283-4336-4c7a-af1b-7cb2d37210d3">

It seems that the model is not outputting any response from this call at `line 60` from `llm_ops.py`. I checked that input  and system values are valid:   

`response_text = self.engine(input_variable.value, system_prompt=system_prompt_value)`

I don't think this has anything to do with my dataset or the contents of the prompt (correct me if I'm wrong!). Does anyone know how to resolve this error?  Thanks!

**Comment by mertyg** [comment]
Without more context it is unclear -- For some reason your response variable is getting initialized with a None value. I am not sure why this may be the case -- perhaps debug what's happening at Line 62 in llm ops?

**Comment by Mehrab-Tanjim** [comment]
I am facing the same problem. @nikhilk7153 is it solved?

**Comment by Mehrab-Tanjim** [comment]
> I am facing the same problem. @nikhilk7153 is it solved?

Seems like the following chunk solves the issue:
```
if isinstance(y, np.int64):
                y = int(y)
```

**Comment by nikhilk7153** [comment]
Hi, I was wondering where exactly you added this code @Mehrab-Tanjim ?

**Comment by Mehrab-Tanjim** [comment]
def eval_sample(item, eval_fn, model):
    """
    This function allows us to evaluate if an answer to a question in the prompt is a good answer.

    """
    x, y = item
    if isinstance(y, np.int64):
        y = int(y)
