### ISSUE TITLE
too long string in openai engine - limit context length

### ISSUE THREAD

**Issue by den-run-ai** [zou-group/textgrad#93]
For prompt optimization example with few hundred samples, the concatenated loss results in too long string and API error.

```python
loss=tg.sum(losses) # len(str(loss)) = 436145
loss.backward() # len(str(gradients)) = 816462
optimizer.step()  # len(str(prompt_update_parameter)) = 1843680
```

results in too long string in openai engine:

```
BadRequestError: Error code: 400 - {'error': {'message': "Invalid 'messages[1].content': string too long. Expected a string with maximum length 1048576, but got a string with length 1843680 instead.", 'type': 'invalid_request_error', 'param': 'messages[1].content', 'code': 'string_above_max_length'}}
```

For now I will try to work-around with prompting the loss to output less tokens.
However it is probably easy to limit the context length and maybe even remove duplicate instructions or enable chunking.

**Comment by den-run-ai** [comment]
I tried cleaning up the instructions in the gradients set with an ad-hoc method, but there seems to be something else much longer passed in the context during optimizer.step(). 
I would appreciate some insight on what is the longest variable passed besides gradients.

**Comment by mertyg** [comment]
I think it's possibly the conversation history. 
In particular, [here](https://github.com/zou-group/textgrad/blob/main/textgrad/optimizer/optimizer_prompts.py#L115) we let the optimizer see the call to the LLM which includes the system prompt / input /   output (can see it [here](https://github.com/zou-group/textgrad/blob/main/textgrad/autograd/llm_backward_prompts.py#L24)). 

If the inputs / outputs are long, this may increase the context size. In earlier experiments we found it fairly helpful to include the whole conversation, but I can see in your case this becomes prohibitive. There should be some ways around this -- you can modify the optimizer prompts (e.g., remove that from the prompt template).

**Comment by den-run-ai** [comment]
thank you, i see now:

len(str(optimizer.parameters[0].gradients_context)) 
#1278111

I think a .reset() on this context would be helpful to resolve this.

**Comment by mertyg** [comment]
You can use `reset_gradients` [here](https://github.com/zou-group/textgrad/blob/main/textgrad/variable.py#L103)
