### ISSUE TITLE
Azrure openai throws an error

### ISSUE THREAD

**Issue by basanthsk** [zou-group/textgrad#98]
ValueError: Please set the OPENAI_API_KEY environment variable if you'd like to use OpenAI models.
Even though I have set 
Environment variables:
        - AZURE_OPENAI_API_KEY: The API key for authenticating with Azure OpenAI.
        - AZURE_OPENAI_API_BASE: The base URL for the Azure OpenAI API.
        - AZURE_OPENAI_API_VERSION: The API version to use. Defaults to '2023-07-01-preview' if not set.
        It is throwing errors I see that 
        this line of code invokes openai class
        super().__init__(cache_path=cache_path, system_prompt=system_prompt, **kwargs)
        leading to ask open ai key
can you guys check or let me know right way to do it

**Comment by vinid** [comment]
Can you share a minimal example to reproduce the error?

**Comment by basanthsk** [comment]
llm_api_test = tg.get_engine(engine_name="azure-gpt-35-turbo")
This itself throw error
